name = "amafuri-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

# KV ネームスペース
# 作成コマンド: npx wrangler kv namespace create amafuri-data
# 作成後に下の id を書き換えてください
[[kv_namespaces]]
binding = "DATA"
id = "530f4c99a7384456a855af864685ae25"

# API_TOKEN は secrets で設定（コマンドラインから）
# npx wrangler secret put API_TOKEN
